# coding: utf-8

"""
    Solar System openData

    API to get all data about all solar system objects  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.bodies_api import BodiesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBodiesApi(unittest.TestCase):
    """BodiesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.bodies_api.BodiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bodies_get(self):
        """Test case for bodies_get

        List  # noqa: E501
        """
        pass

    def test_bodies_id_get(self):
        """Test case for bodies_id_get

        read  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
