# coding: utf-8

# flake8: noqa
"""
    Solar System openData

    API to get all data about all solar system objects  # noqa: E501

    OpenAPI spec version: 1.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
